apiVersion: v1
kind: Service
metadata:
  name: feedback-app-frontend-service
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: feedback-app-frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-app-frontend
  labels:
    app: feedback-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-app-frontend
  template:
    metadata:
      labels:
        app: feedback-app-frontend
    spec:
      containers:
      - name: feedback-app-frontend
        image: tasil/feedback-app-frontend:v3.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"  
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
          name: nginx-config-volume
      volumes:
      - name: nginx-config-volume
        configMap:
          name: feedback-nginx-configmap
          items:
          - key: nginx.conf
            path: nginx.conf

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: feedback-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: feedback-app-frontend  
  minReplicas: 1                 
  maxReplicas: 4              
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50